import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
// `copertura <file>`: one build mapped back to the sources, for
// tests/copertura.mjs (npm run test:copertura). Never the release.
const coverage = process.argv[2] === 'copertura' ? process.argv[3] : undefined;
// `mappa <file>`: the production build again, with its source map written
// beside it and not referenced in the file, so the code is the release's: the
// real-app tests map the plugin's errors back to the sources. Never the release.
const mapped = process.argv[2] === 'mappa' ? process.argv[3] : undefined;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: mapped ? 'external' : prod ? false : 'inline',
	treeShaking: true,
	outfile: coverage ?? mapped ?? 'main.js',
	minify: prod || Boolean(mapped),
});

if (prod || coverage || mapped) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
